---
name: RDF-Sesame
version: 0.11
author:
  - Michael Hendricks <michael@palmcluster.org>
abstract: Interact with Sesame RDF servers
license: perl
requires:
  Carp: 0
  Data::Table: 0
  LWP::UserAgent: 0
  Test::More: 0.31
  URI: 0
  XML::Simple: 0
provides:
  RDF::Sesame:
    file: lib/RDF/Sesame.pm
    version: 0.11
  RDF::Sesame::Connection:
    file: lib/RDF/Sesame/Connection.pm
  RDF::Sesame::Repository:
    file: lib/RDF/Sesame/Repository.pm
  RDF::Sesame::Response:
    file: lib/RDF/Sesame/Response.pm
  RDF::Sesame::TableResult:
    file: lib/RDF/Sesame/TableResult.pm
generated_by: Module::Build version 0.23
